[package]
name = "job-finding"
version = "1.0.0"
description = "中国企业招聘信息平台 - Fortune China 500 CS专场"
authors = ["hongyunnnn"]
edition = "2021"

[lib]
name = "job_finding_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
